// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MVCBlog.Domain.Data;
using System;

namespace MVCBlog.Domain.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20180318131157_DBSETConfig")]
    partial class DBSETConfig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCBlog.Domain.Entities.Essay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnName("BODY");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnName("PUBLISH_DATE");

                    b.Property<string>("Subtitle")
                        .HasColumnName("SUBTITLE")
                        .HasMaxLength(200);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("TITLE")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("ESSAY");
                });
#pragma warning restore 612, 618
        }
    }
}
